---
title: "3.ch1-latex-formatting"
author: "Ivara Goulden"
date: "2026-03-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Count formula: $C \sim \text{negative binomial} (\alpha + \alpha_{[sp, rt]} + \beta_{[sp]} * \text{year} + \beta_{\text{obs}} * \text{observer quality}, \theta) \\ \theta \sim \text{gamma}(2,1)$

FULL FORMULA: $C \sim \text{negative binomial} (\alpha + \alpha_{[sp, rt]} + \beta_{[sp]} * \text{year} + \beta_{\text{obs}} * \text{observer quality}, \theta) \\ \alpha \sim \text{normal}(0,2) \\ \alpha_{[sp,rt]} \sim \text{normal}(0,1) \\  \beta_{[sp]} \sim (\gamma_{\beta} + \kappa_{\text{temp.niche}} * \text{temperature niche position}_{[sp]} ... \kappa_{\text{regional.trend}} * \text{regional trend}_{[sp]} , \sigma_{\beta}) \\ \beta_{\text[obs]} \sim \text{normal}(0,0.5) \\ \theta \sim \text{gamma}(2,1)$

Overdispersion prior: $\theta \sim \text{gamma}(2,1)$

Effects of observer skill formula: $\text{observer quality} = \frac{N_{[rt, yr, obs_f]} - \text{mean}(N_{[rt, obs_a]})}{\text{mean}(N_{[rt, obs_a]})}$

Traits formula: $\beta_{[sp]} \sim (\gamma_{\beta} + \\ \kappa_{\text{temp.niche}} * \text{temperature niche position}_{[sp]} + \\ \kappa_{\text{perc.insect}} * \text{percent insectivory}_{[sp]} + \\ \kappa_{\text{hab.select}} * \text{habitat selectivity}_{[sp]} + \\ \kappa_{\text{regional.trend}} * \text{regional trend}_{[sp]} , \\ \sigma_{\beta})$

Trait priors: $\kappa_{\text{[temp.niche : regional.trend]}} \sim \text{normal}(0, 1)$

Regional Trend: $\text{USGS Regional Trend}_{[sp]} \sim \text{normal}( \text{Modeled Regional Trend}_{[sp]}, \text{USGS }\sigma_{[sp]}) \\ \text{Modeled Regional Trend}_{[sp]} \sim \text{normal}(\mu_{\text{regional.trend}}, \sigma_{\text{regional.trend}}) \\ \mu_{\text{regional.trend}} \sim \text{normal}(0,1.5) \\ \sigma_{\text{regional.trend}} \sim \text{half-normal}(0,0.5) $



